import { msg, type MessageKey } from '../i18n';

// Translate display labels only. Provider identifiers still drive filtering and matching.
const genres: Record<string, MessageKey> = {
  "action": 'games.genreAction',
  "экшен": 'games.genreAction',
  "экшены": 'games.genreAction',
  "role-playing (rpg)": 'games.genreRPG',
  "ролевые": 'games.genreRPG',
  "rpg": 'games.genreRPG',
  "ролевые игры": 'games.genreRPG',
  "shooter": 'games.genreShooter',
  "шутеры": 'games.genreShooter',
  "adventure": 'games.genreAdventure',
  "приключения": 'games.genreAdventure',
  "приключенческие игры": 'games.genreAdventure',
  "strategy": 'games.genreStrategy',
  "стратегии": 'games.genreStrategy',
  "indie": 'games.genreIndie',
  "инди": 'games.genreIndie',
  "arcade": 'games.genreArcade',
  "аркады": 'games.genreArcade',
  "card & board game": 'games.genreCardBoard',
  "карточные и настольные игры": 'games.genreCardBoard',
  "casual": 'games.genreCasual',
  "казуальные игры": 'games.genreCasual',
  "fighting": 'games.genreFighting',
  "файтинги": 'games.genreFighting',
  "hack and slash/beat 'em up": 'games.genreHackSlash',
  "слэшеры и beat ’em up": 'games.genreHackSlash',
  "massively multiplayer": 'games.genreMultiplayer',
  "массовые многопользовательские игры": 'games.genreMultiplayer',
  "массовая многопользовательская игра": 'games.genreMultiplayer',
  "многопользовательские игры": 'games.genreMultiplayer',
  "moba": 'games.genreMOBA',
  "music": 'games.genreMusic',
  "музыкальные игры": 'games.genreMusic',
  "pinball": 'games.genrePinball',
  "пинбол": 'games.genrePinball',
  "platform": 'games.genrePlatform',
  "платформеры": 'games.genrePlatform',
  "platformer": 'games.genrePlatform',
  "point-and-click": 'games.genrePointClick',
  "puzzle": 'games.genrePuzzle',
  "головоломки": 'games.genrePuzzle',
  "quiz/trivia": 'games.genreQuiz',
  "викторины": 'games.genreQuiz',
  "racing": 'games.genreRacing',
  "гонки": 'games.genreRacing',
  "real time strategy (rts)": 'games.genreRTS',
  "стратегии в реальном времени": 'games.genreRTS',
  "simulator": 'games.genreSimulator',
  "симуляторы": 'games.genreSimulator',
  "simulation": 'games.genreSimulator',
  "sport": 'games.genreSport',
  "спорт": 'games.genreSport',
  "sports": 'games.genreSport',
  "tactical": 'games.genreTactical',
  "тактические игры": 'games.genreTactical',
  "turn-based strategy (tbs)": 'games.genreTBS',
  "пошаговые стратегии": 'games.genreTBS',
  "visual novel": 'games.genreVisualNovel',
  "визуальные новеллы": 'games.genreVisualNovel',
};

const themes: Record<string, MessageKey> = {
  "action": 'games.themeAction',
  "экшен": 'games.themeAction',
  "fantasy": 'games.themeFantasy',
  "фэнтези": 'games.themeFantasy',
  "science fiction": 'games.themeScienceFiction',
  "научная фантастика": 'games.themeScienceFiction',
  "horror": 'games.themeHorror',
  "ужасы": 'games.themeHorror',
  "thriller": 'games.themeThriller',
  "триллер": 'games.themeThriller',
  "survival": 'games.themeSurvival',
  "выживание": 'games.themeSurvival',
  "historical": 'games.themeHistorical',
  "история": 'games.themeHistorical',
  "stealth": 'games.themeStealth',
  "скрытность": 'games.themeStealth',
  "comedy": 'games.themeComedy',
  "комедия": 'games.themeComedy',
  "business": 'games.themeBusiness',
  "бизнес": 'games.themeBusiness',
  "drama": 'games.themeDrama',
  "драма": 'games.themeDrama',
  "non-fiction": 'games.themeNonFiction',
  "документальные": 'games.themeNonFiction',
  "sandbox": 'games.themeSandbox',
  "песочница": 'games.themeSandbox',
  "educational": 'games.themeEducational',
  "обучение": 'games.themeEducational',
  "kids": 'games.themeKids',
  "для детей": 'games.themeKids',
  "open world": 'games.themeOpenWorld',
  "открытый мир": 'games.themeOpenWorld',
  "warfare": 'games.themeWarfare',
  "военные": 'games.themeWarfare',
  "party": 'games.themeParty',
  "для компании": 'games.themeParty',
  "mystery": 'games.themeMystery',
  "тайны": 'games.themeMystery',
  "erotic": 'games.themeErotic',
  "эротика": 'games.themeErotic',
  "romance": 'games.themeRomance',
  "романтика": 'games.themeRomance',
  "multiplayer": 'games.themeMultiplayer',
  "мультиплеер": 'games.themeMultiplayer',
};

export function genreLabel(value: string): string {
  const key = Object.hasOwn(genres, value.trim().toLowerCase()) ? genres[value.trim().toLowerCase()] : undefined;
  return key ? msg(key) : value;
}

export function themeLabel(value: string): string {
  const key = Object.hasOwn(themes, value.trim().toLowerCase()) ? themes[value.trim().toLowerCase()] : undefined;
  return key ? msg(key) : value;
}
