import { errorCode, msg } from '../i18n';
import type { MessageKey } from '../i18n';

export const REASONS: Record<string, MessageKey> = {
  'install.bad_command': 'errInstall.installBadCommand',
  'install.busy': 'errInstall.installBusy',
  'install.copy_verify_failed': 'errInstall.installCopyVerifyFailed',
  'install.dest_exists': 'errInstall.installDestExists',
  'install.dest_not_empty': 'errInstall.installDestNotEmpty',
  'install.elevation_declined': 'errInstall.installElevationDeclined',
  'install.empty_destination': 'errInstall.installEmptyDestination',
  'install.empty_install': 'errInstall.installEmptyInstall',
  'install.empty_installer_path': 'errInstall.installEmptyInstallerPath',
  'install.empty_source': 'errInstall.installEmptySource',
  'install.external_runs': 'errInstall.installExternalRuns',
  'install.files_locked': 'errInstall.installFilesLocked',
  'install.free_space_unknown': 'errInstall.installFreeSpaceUnknown',
  'install.game_busy': 'errInstall.installGameBusy',
  'install.game_running': 'errInstall.installGameRunning',
  'install.incomplete_source': 'errInstall.installIncompleteSource',
  'install.installer_busy': 'errInstall.installInstallerBusy',
  'install.installer_cancelled': 'errInstall.installInstallerCancelled',
  'install.installer_failed': 'errInstall.installInstallerFailed',
  'install.installer_no_output': 'errInstall.installInstallerNoOutput',
  'install.installer_not_confirmed_stopped': 'errInstall.installInstallerNotConfirmedStopped',
  'install.installer_still_running': 'errInstall.installInstallerStillRunning',
  'install.mixed_installers': 'errInstall.installMixedInstallers',
  'install.needs_user': 'errInstall.installNeedsUser',
  'install.nested_paths': 'errInstall.installNestedPaths',
  'install.no_destination': 'errInstall.installNoDestination',
  'install.no_downloads': 'errInstall.installNoDownloads',
  'install.no_elevated_process': 'errInstall.installNoElevatedProcess',
  'install.no_executable': 'errInstall.installNoExecutable',
  'install.no_library': 'errInstall.installNoLibrary',
  'install.no_library_access': 'errInstall.installNoLibraryAccess',
  'install.no_silent': 'errInstall.installNoSilent',
  'install.no_source': 'errInstall.installNoSource',
  'install.no_uninstaller': 'errInstall.installNoUninstaller',
  'install.non_regular_file': 'errInstall.installNonRegularFile',
  'install.not_completed': 'errInstall.installNotCompleted',
  'install.not_dir': 'errInstall.installNotDir',
  'install.not_enough_space': 'errInstall.installNotEnoughSpace',
  'install.not_found': 'errInstall.installNotFound',
  'install.nothing_to_remove': 'errInstall.installNothingToRemove',
  'install.outside_install': 'errInstall.installOutsideInstall',
  'install.relative_destination': 'errInstall.installRelativeDestination',
  'install.remove_seeding': 'errInstall.installRemoveSeeding',
  'install.symlink_privilege': 'errInstall.installSymlinkPrivilege',
  'install.unavailable': 'errInstall.installUnavailable',
  'install.uninstall_cancelled': 'errInstall.installUninstallCancelled',
  'install.uninstall_failed': 'errInstall.installUninstallFailed',
  'install.unknown_type': 'errInstall.installUnknownType',
  'install.unrecognized_source': 'errInstall.installUnrecognizedSource',
  'install.unsafe_removal': 'errInstall.installUnsafeRemoval',
  'install.unsupported_archive': 'errInstall.installUnsupportedArchive',
  'install.worker_not_finished': 'errInstall.installWorkerNotFinished',

  'download.add_torrent_failed': 'errInstall.downloadAddTorrentFailed',
  'download.bad_paths': 'errInstall.downloadBadPaths',
  'download.bad_sizes': 'errInstall.downloadBadSizes',
  'download.blocked_by_av': 'errInstall.downloadBlockedByAv',
  'download.destination_permission': 'errInstall.downloadDestinationPermission',
  'download.destination_unavailable': 'errInstall.downloadDestinationUnavailable',
  'download.disk_write_failed': 'errInstall.downloadDiskWriteFailed',
  'download.duplicate_download': 'errInstall.downloadDuplicateDownload',
  'download.empty_destination': 'errInstall.downloadEmptyDestination',
  'download.empty_source': 'errInstall.downloadEmptySource',
  'download.file_incomplete': 'errInstall.downloadFileIncomplete',
  'download.file_missing': 'errInstall.downloadFileMissing',
  'download.file_oversized': 'errInstall.downloadFileOversized',
  'download.file_stat_failed': 'errInstall.downloadFileStatFailed',
  'download.file_truncated': 'errInstall.downloadFileTruncated',
  'download.hash_busy': 'errInstall.downloadHashBusy',
  'download.invalid_magnet': 'errInstall.downloadInvalidMagnet',
  'download.metadata_required': 'errInstall.downloadMetadataRequired',
  'download.no_client': 'errInstall.downloadNoClient',
  'download.no_files_selected': 'errInstall.downloadNoFilesSelected',
  'download.no_free_space': 'errInstall.downloadNoFreeSpace',
  'download.no_metadata': 'errInstall.downloadNoMetadata',
  'download.not_enough_space': 'errInstall.downloadNotEnoughSpace',
  'download.not_found': 'errInstall.downloadNotFound',
  'download.restore_failed': 'errInstall.downloadRestoreFailed',
  'download.seeding': 'errInstall.downloadSeeding',
  'download.torrent_read_failed': 'errInstall.downloadTorrentReadFailed',
  'download.unavailable': 'errInstall.downloadUnavailable',
};

export function installErrorText(err: unknown, fallback: string = msg('errInstall.fallback')): string {
  const key = REASONS[errorCode(err)];
  return key ? msg(key) : fallback;
}
